# NOTE: this is not production deployment script. It's just for testing purposes
version: "3.9"
services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  core-api:
    image: registry.digitalocean.com/kotal/core-api:develop
    ports:
      - 8080:8080
    environment:
      MOCK: "true"
      DB_SERVER_URL: postgres://postgres:secret@postgres:5432/postgres
      CLOUD_API_SERVER_PORT: 8080
    restart: on-failure
    depends_on:
      - postgres
