name: Build-Push-staging-cloud-api

on:
  push:
    branches:
      - master
      - test/helm-chart
  pull_request:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            docker.io/kotalco/cloud-api
          tags: |
            type=ref,event=tag
            type=sha,prefix=,suffix=,format=short
          flavor: |
            latest=true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: kotalco
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
            EC_PUBLIC_KEY=${{ secrets.STAGING_EC_PUBLIC_KEY }}
  test-on-digital-ocean:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Checkout kotal-helm-chart Repo
        uses: actions/checkout@v3
        with:
          repository: kotalco/kotal-helm-chart
          path: kotal-helm-chart

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Add helm dependencies repositories
        run: |
          for dir in $(ls -d kotal-helm-chart/charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      - name: Testing Kotal-Helm-Chart with Cloud-api new image
        uses: 'vimeda/helm@v1.6.8'
        with:
          release: 'kotal'
          namespace: 'kotal'
          chart: 'kotal-helm-chart/charts/kotal'
          helm: 'helm3'
          token: '${{ github.token }}'
          values: |
            api.tag: ${SHORT_SHA}
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_DO_TESTING }}'
