name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DIGITAL_OCEAN_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.DIGITAL_OCEAN_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      env:
        GITHUB_SHA: ${{ env.GITHUB_SHA }}
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: registry.digitalocean.com/kotal/cloud-api:$GITHUB_SHA
