name: Go build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Run Postgres Database
      run: docker run -d --name kotal-database -p 5432:5432 -e POSTGRES_PASSWORD=secret postgres
    
    - name: Test
      run: DB_SERVER_URL=postgres://postgres:secret@localhost:5432/postgres go test -v ./...
