name: Testing-Helm-Chart
# Only trigger, when the Build-Push-cloud-api workflow succeeded

on:
  workflow_run:
    workflows: [Build-Push-staging-cloud-api, Build-Push-production-cloud-api]
    types:
      - completed
    branches: [test/helm-chart]

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Checkout kotal-helm-chart Repo
        uses: actions/checkout@v3
        with:
          repository: kotalco/kotal-helm-chart
          path: kotal-helm-chart

      - name: Testing Kotal-Helm-Chart with Cloud-api new image
        uses: 'vimeda/helm@v1.6.8'
        with:
          release: 'kotal'
          namespace: 'kotal'
          chart: 'kotal-helm-chart/charts/kotal'
          helm: 'helm3'
          token: '${{ github.token }}'
          values: |
            api.tag: ${SHORT_SHA}
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_DO_TESTING }}'



